name: sinav_social
description: A new Flutter project.

publish_to: "none"

version: 1.0.19+34

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  about: ^2.1.1
  advanced_in_app_review: ^1.1.0
  animated_search_bar: ^2.2.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  firebase_core: ^1.5.0
  firebase_messaging: ^12.0.2
  firebase_messaging_platform_interface: ^4.1.1
  flame: ^1.0.0-releasecandidate.11
  flip_card: ^0.6.0
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  flutter_local_notifications: ^9.5.0
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  flutter_painter: ^1.0.1
  flutter_pdfview: ^1.2.3
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.0
  get: ^4.6.1
  get_it: ^7.2.0
  google_fonts: 2.1.1
  google_sign_in: ^5.4.2
  helpers: ^1.1.4
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  http: ^0.13.4
  image_cropper: ^3.0.0
  image_picker: ^0.8.5+3
  in_app_review: ^2.0.4
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  launch_review: ^3.0.1
  loadmore: ^2.0.1
  logger: ^1.1.0
  logging: ^1.0.2
  lottie: null
  material_design_icons_flutter: ^5.0.6595
  modal_bottom_sheet: ^2.0.0
  package_info_plus: ^1.4.2
  path_provider: null
  phosphor_flutter: ^1.4.0
  photo_view: ^0.14.0
  platform_device_id: ^1.0.1
  provider: ^6.0.3
  scoped_model: ^1.0.1
  sentry_flutter: ^6.11.1
  share_plus: ^4.0.10
  shared_preferences: ^2.0.12
  simple_animations: ^4.0.1
  socket_io_client: ^1.0.2
  sprintf: ^6.0.2
  sudoku_dart: ^0.1.0
  swipe_to: null
  swiping_card_deck: ^1.2.0
  syncfusion_flutter_datepicker: 20.4.44
  tflite: ^1.1.2
  timezone: ^0.8.0
  tuple: ^2.0.0
  vsync_provider: ^0.5.0
  webview_flutter: ^3.0.4
  flutter_linkify: ^5.0.2
  percent_indicator: ^4.0.1
  
dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.8
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"

flutter:
  assets:
    - assets/images/logo.png
    - assets5/images/

    - assets4/audio/piece_moved.mp3

    - assets3/images/

    - assets2/
    - assets2/images/

    - assets/
    - assets/images/
    - assets/icons/
    - assets/lottie_animations/
    - assets/audio/piece_moved.mp3
    - assets/images/pieces/8-bit/
    - assets/images/pieces/angular/
    - assets/images/pieces/classic/
    - assets/images/pieces/letters/
    - assets/images/pieces/lewischessmen/
    - assets/images/pieces/mexicocity/
    - assets/images/pieces/videochess/
    - assets/card_images/card_1_image.jpg
    - assets/card_images/card_2_image.jpg
    - assets/card_images/card_3_image.jpg
    - assets/card_images/card_4_image.jpg


  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets3/Permanent_Marker/PermanentMarker-Regular.ttf
    - family: Jura
      fonts:
        - asset: assets4/font/Jura-VariableFont_wght.ttf

  uses-material-design: true
